### ISSUE TITLE
standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by MurasameCyan** [fireph/docker-twitch-drops-miner#2]
oh, can you add arm support?  pls

**Comment by fireph** [comment]
> oh, can you add arm support? pls

I have no idea how to do this or how it is implemented. Is ARM supported by the base `jlesage/baseimage-gui:ubuntu-22.04-v4` image? If not then there's no way to add support without using a different base image (and this one works great for me, so I'm not inclined to rewrite the whole thing).

**Comment by fireph** [comment]
I did change around the build a bit, arm might work now 🤷
